project:
  type: website

website:
  title: "flir"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Rules"
        href: rules.qmd
      - text: "Development"
        href: development.qmd
      - text: "About"
        href: about.qmd

  sidebar:
    - title: "Rules"
      style: "docked"
      background: light
      contents:
        - rules.qmd
        - rules/any_is_na.qmd
        - rules/class_equals.qmd


# format:
#   html:
#     theme:
#       - cosmo
#       - brand
#     css: styles.css
#     toc: true
